{% set name = "fastcore" %}
{% set version = "1.7.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastcore-{{ version }}.tar.gz
  sha256: 4b10701e0d4ca866e83ce23aea79828dfb3ee7437689e17d58936c9b3cbfce7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - py2pyi=fastcore.py2pyi:py2pyi
    - replace_wildcards=fastcore.py2pyi:replace_wildcards

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - pip
  run:
    - python >=3.8
    - packaging

test:
  imports:
    - fastcore
  commands:
    - pip check
    - py2pyi --help
    - replace_wildcards --help
  requires:
    - pip

about:
  home: https://github.com/fastai/fastcore
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
    - synapticarbors
