{% set name = "fastcore" %}
{% set version = "1.5.47" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcore-{{ version }}.tar.gz
  sha256: cc7585482bb00cbffc0f673fc0ac4db1423df7bff0265892732e1eafa5455563

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - packaging
    - pip
    - python >=3.6

test:
  imports:
    - fastcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastcore/tree/master/
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
