{% set name = "fastcore" %}
{% set version = "1.6.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcore-{{ version }}.tar.gz
  sha256: 91b1da4d2cd4db7c5e9effde583371a7f0189b229f1e13a466c3a58a87a7b28f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - py2pyi=fastcore.py2pyi:py2pyi
    - replace_wildcards=fastcore.py2pyi:replace_wildcards

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - packaging
    - python >=3.8

test:
  imports:
    - fastcore
  commands:
    - pip check
    - py2pyi --help
    - replace_wildcards --help
  requires:
    - pip

about:
  home: https://github.com/fastai/fastcore
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
    - synapticarbors
