{% set name = "fastcore" %}
{% set version = "1.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcore-{{ version }}.tar.gz
  sha256: cb4baf4cc72ed42b73df49aecafdb3842a9eda0f33741a5930bfeb97df272cc5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - packaging
    - python >=3.8

test:
  imports:
    - fastcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastcore/tree/master/
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
    - synapticarbors
