{% set name = "fastcore" %}
{% set version = "1.5.45" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcore-{{ version }}.tar.gz
  sha256: b8a3489b72e205860647773db4781aa33aeedb1906939a7cf89d664b8e023fd3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - packaging
    - pip
    - python >=3.6

test:
  imports:
    - fastcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastcore/tree/master/
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
