context:
  version: 1.8.0

package:
  name: fastcore
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastcore/fastcore-${{ version }}.tar.gz
  sha256: d23e63aff4bcd06dde24cdf9f7ea13c48e7d274ae89e52e826df33c64869c976

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - py2pyi=fastcore.py2pyi:py2pyi
      - replace_wildcards=fastcore.py2pyi:replace_wildcards

requirements:
  host:
    - python ${{ python_min }}
    - setuptools >=64.0
    - pip
  run:
    - python >=${{ python_min }}
    - packaging

tests:
  - python:
      imports:
        - fastcore
      pip_check: true
  - script:
      - py2pyi --help
      - replace_wildcards --help
    requirements:
      run:
        - python ${{ python_min }}

about:
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/fastai/fastcore

extra:
  recipe-maintainers:
    - kai-tub
    - synapticarbors
    - thewchan
