context:
  version: 1.7.20
  python_min: "3.8"

package:
  name: fastcore
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/fastcore/fastcore-${{ version }}.tar.gz
  sha256: 316dcb0e2d5e338e069f338b3c136ca9eb4ce950ca433da2a80952fc5928ddab

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - py2pyi=fastcore.py2pyi:py2pyi
      - replace_wildcards=fastcore.py2pyi:replace_wildcards

requirements:
  host:
    - python ${{ python_min }}
    - setuptools >=64.0
    - pip
  run:
    - python >=${{ python_min }}
    - packaging

tests:
  - python:
      imports:
        - fastcore
      pip_check: true
  - script:
      - py2pyi --help
      - replace_wildcards --help
    requirements:
      run:
        - python ${{ python_min }}

about:
  summary: Python supercharged for fastai development
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/fastai/fastcore

extra:
  recipe-maintainers:
    - kai-tub
    - synapticarbors
